import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Logo from '../components/Logo';
import Navigation from '../components/Navigation';
import '../styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Wild Oasis',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className='bg-primary-950 text-primary-100 min-h-screen'>
				<header>
					<Logo />
					<Navigation />
				</header>
				<main>{children}</main>

				<footer>copyright by wild oasis</footer>
			</body>
		</html>
	);
}
